import type { ThemeValues } from "@repo/tokens";

/** Themes modelled on the look of well-known sites, to check how far tokens alone go. */
export const themes = {
  product: {
    brandColor: "#5e6ad2",
    accentColor: null,
    neutral: "cool",
    colorMode: "dark",
    fonts: { heading: "inter", body: "inter" },
    typeScale: "medium",
    headingWeight: 500,
    headingStyle: "tight",
    labelStyle: "mono",
    radius: "small",
    buttons: "pill",
    cards: "outline",
    density: "spacious",
    width: "wide",
    imageCorners: "rounded",
    motion: true,
  },
  luxury: {
    brandColor: "#5b4636",
    accentColor: null,
    neutral: "warm",
    colorMode: "light",
    fonts: { heading: "cormorant-garamond", body: "instrument-sans" },
    typeScale: "small",
    headingWeight: 400,
    headingStyle: "normal",
    labelStyle: "plain",
    radius: "none",
    buttons: "rounded",
    cards: "filled",
    density: "spacious",
    width: "regular",
    imageCorners: "square",
    motion: true,
  },
  museum: {
    brandColor: "#6b1f1f",
    accentColor: "#85dee7",
    neutral: "neutral",
    colorMode: "light",
    fonts: { heading: "archivo", body: "ibm-plex-sans" },
    typeScale: "large",
    headingWeight: 500,
    headingStyle: "uppercase",
    labelStyle: "uppercase",
    radius: "none",
    buttons: "rounded",
    cards: "outline",
    density: "comfortable",
    width: "regular",
    imageCorners: "square",
    motion: false,
  },
  friendly: {
    brandColor: "#0061ef",
    accentColor: "#ffce00",
    neutral: "warm",
    colorMode: "light",
    fonts: { heading: "plus-jakarta-sans", body: "plus-jakarta-sans" },
    typeScale: "medium",
    headingWeight: 800,
    headingStyle: "tight",
    labelStyle: "pill",
    radius: "large",
    buttons: "pill",
    cards: "filled",
    density: "comfortable",
    width: "wide",
    imageCorners: "extra-rounded",
    motion: true,
  },
  nonprofit: {
    brandColor: "#1d4ed8",
    accentColor: "#ffc907",
    neutral: "warm",
    colorMode: "light",
    fonts: { heading: "newsreader", body: "dm-sans" },
    typeScale: "large",
    headingWeight: 400,
    headingStyle: "normal",
    labelStyle: "uppercase",
    radius: "small",
    buttons: "rounded",
    cards: "raised",
    density: "comfortable",
    width: "regular",
    imageCorners: "rounded",
    motion: true,
  },
  editorial: {
    brandColor: "#111111",
    accentColor: null,
    neutral: "neutral",
    colorMode: "light",
    fonts: { heading: "geist", body: "geist" },
    typeScale: "x-large",
    headingWeight: 500,
    headingStyle: "tight",
    labelStyle: "mono",
    radius: "medium",
    buttons: "pill",
    cards: "outline",
    density: "spacious",
    width: "wide",
    imageCorners: "rounded",
    motion: true,
  },
} as const satisfies Record<string, ThemeValues>;
