// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import callToAction1banner from "./call-to-action/v1/fixtures/banner.json" with { type: "json" };
import callToAction1centered from "./call-to-action/v1/fixtures/centered.json" with { type: "json" };
import callToAction1placeholder from "./call-to-action/v1/fixtures/placeholder.json" with { type: "json" };
import contactDetails1columns from "./contact-details/v1/fixtures/columns.json" with { type: "json" };
import contactDetails1placeholder from "./contact-details/v1/fixtures/placeholder.json" with { type: "json" };
import contactDetails1stacked from "./contact-details/v1/fixtures/stacked.json" with { type: "json" };
import contactDetails2cards from "./contact-details/v2/fixtures/cards.json" with { type: "json" };
import contactDetails2columns from "./contact-details/v2/fixtures/columns.json" with { type: "json" };
import contactDetails2placeholder from "./contact-details/v2/fixtures/placeholder.json" with { type: "json" };
import contactDetails2split from "./contact-details/v2/fixtures/split.json" with { type: "json" };
import eventCard1default from "./event-card/v1/fixtures/default.json" with { type: "json" };
import eventCard1placeholder from "./event-card/v1/fixtures/placeholder.json" with { type: "json" };
import eventCard2default from "./event-card/v2/fixtures/default.json" with { type: "json" };
import eventCard2noImage from "./event-card/v2/fixtures/no-image.json" with { type: "json" };
import eventCard2placeholder from "./event-card/v2/fixtures/placeholder.json" with { type: "json" };
import eventCards1grid from "./event-cards/v1/fixtures/grid.json" with { type: "json" };
import eventCards1list from "./event-cards/v1/fixtures/list.json" with { type: "json" };
import eventCards1placeholder from "./event-cards/v1/fixtures/placeholder.json" with { type: "json" };
import eventCards2gridTwo from "./event-cards/v2/fixtures/grid-two.json" with { type: "json" };
import eventCards2grid from "./event-cards/v2/fixtures/grid.json" with { type: "json" };
import eventCards2list from "./event-cards/v2/fixtures/list.json" with { type: "json" };
import eventCards2placeholder from "./event-cards/v2/fixtures/placeholder.json" with { type: "json" };
import faq1list from "./faq/v1/fixtures/list.json" with { type: "json" };
import faq1placeholder from "./faq/v1/fixtures/placeholder.json" with { type: "json" };
import faq1twoColumns from "./faq/v1/fixtures/two-columns.json" with { type: "json" };
import featureGrid1placeholder from "./feature-grid/v1/fixtures/placeholder.json" with { type: "json" };
import featureGrid1threeColumns from "./feature-grid/v1/fixtures/three-columns.json" with { type: "json" };
import featureGrid1twoColumns from "./feature-grid/v1/fixtures/two-columns.json" with { type: "json" };
import featureGrid2grid from "./feature-grid/v2/fixtures/grid.json" with { type: "json" };
import featureGrid2list from "./feature-grid/v2/fixtures/list.json" with { type: "json" };
import featureGrid2placeholder from "./feature-grid/v2/fixtures/placeholder.json" with { type: "json" };
import featureGrid2split from "./feature-grid/v2/fixtures/split.json" with { type: "json" };
import featureItem1default from "./feature-item/v1/fixtures/default.json" with { type: "json" };
import featureItem1placeholder from "./feature-item/v1/fixtures/placeholder.json" with { type: "json" };
import featureItem2default from "./feature-item/v2/fixtures/default.json" with { type: "json" };
import featureItem2image from "./feature-item/v2/fixtures/image.json" with { type: "json" };
import featureItem2placeholder from "./feature-item/v2/fixtures/placeholder.json" with { type: "json" };
import footer1columns from "./footer/v1/fixtures/columns.json" with { type: "json" };
import footer1simple from "./footer/v1/fixtures/simple.json" with { type: "json" };
import footer2centered from "./footer/v2/fixtures/centered.json" with { type: "json" };
import footer2columns from "./footer/v2/fixtures/columns.json" with { type: "json" };
import footer2simple from "./footer/v2/fixtures/simple.json" with { type: "json" };
import footer2wordmark from "./footer/v2/fixtures/wordmark.json" with { type: "json" };
import formSection1card from "./form-section/v1/fixtures/card.json" with { type: "json" };
import formSection1placeholder from "./form-section/v1/fixtures/placeholder.json" with { type: "json" };
import formSection1plain from "./form-section/v1/fixtures/plain.json" with { type: "json" };
import formSection2card from "./form-section/v2/fixtures/card.json" with { type: "json" };
import formSection2inlineInset from "./form-section/v2/fixtures/inline-inset.json" with { type: "json" };
import formSection2inline from "./form-section/v2/fixtures/inline.json" with { type: "json" };
import formSection2placeholder from "./form-section/v2/fixtures/placeholder.json" with { type: "json" };
import formSection2split from "./form-section/v2/fixtures/split.json" with { type: "json" };
import gallery1grid from "./gallery/v1/fixtures/grid.json" with { type: "json" };
import gallery1placeholder from "./gallery/v1/fixtures/placeholder.json" with { type: "json" };
import gallery1wide from "./gallery/v1/fixtures/wide.json" with { type: "json" };
import header1centered from "./header/v1/fixtures/centered.json" with { type: "json" };
import header1simple from "./header/v1/fixtures/simple.json" with { type: "json" };
import header2centered from "./header/v2/fixtures/centered.json" with { type: "json" };
import header2simple from "./header/v2/fixtures/simple.json" with { type: "json" };
import header3centeredLogo from "./header/v3/fixtures/centered-logo.json" with { type: "json" };
import header3centeredMenu from "./header/v3/fixtures/centered-menu.json" with { type: "json" };
import header3floating from "./header/v3/fixtures/floating.json" with { type: "json" };
import header3standard from "./header/v3/fixtures/standard.json" with { type: "json" };
import hero1centered from "./hero/v1/fixtures/centered.json" with { type: "json" };
import hero1placeholder from "./hero/v1/fixtures/placeholder.json" with { type: "json" };
import hero1splitImage from "./hero/v1/fixtures/split-image.json" with { type: "json" };
import hero2centered from "./hero/v2/fixtures/centered.json" with { type: "json" };
import hero2placeholder from "./hero/v2/fixtures/placeholder.json" with { type: "json" };
import hero2splitImage from "./hero/v2/fixtures/split-image.json" with { type: "json" };
import hero3centered from "./hero/v3/fixtures/centered.json" with { type: "json" };
import hero3fullBleed from "./hero/v3/fixtures/full-bleed.json" with { type: "json" };
import hero3placeholder from "./hero/v3/fixtures/placeholder.json" with { type: "json" };
import hero3splitImage from "./hero/v3/fixtures/split-image.json" with { type: "json" };
import hero4cover from "./hero/v4/fixtures/cover.json" with { type: "json" };
import hero4editorial from "./hero/v4/fixtures/editorial.json" with { type: "json" };
import hero4panel from "./hero/v4/fixtures/panel.json" with { type: "json" };
import hero4placeholder from "./hero/v4/fixtures/placeholder.json" with { type: "json" };
import hero4split from "./hero/v4/fixtures/split.json" with { type: "json" };
import hero4stacked from "./hero/v4/fixtures/stacked.json" with { type: "json" };
import imageCaption1narrow from "./image-caption/v1/fixtures/narrow.json" with { type: "json" };
import imageCaption1placeholder from "./image-caption/v1/fixtures/placeholder.json" with { type: "json" };
import imageCaption1wide from "./image-caption/v1/fixtures/wide.json" with { type: "json" };
import location1imageLeft from "./location/v1/fixtures/image-left.json" with { type: "json" };
import location1imageRight from "./location/v1/fixtures/image-right.json" with { type: "json" };
import location1placeholder from "./location/v1/fixtures/placeholder.json" with { type: "json" };
import location2placeholder from "./location/v2/fixtures/placeholder.json" with { type: "json" };
import location2splitStart from "./location/v2/fixtures/split-start.json" with { type: "json" };
import location2split from "./location/v2/fixtures/split.json" with { type: "json" };
import location2stacked from "./location/v2/fixtures/stacked.json" with { type: "json" };
import logoStrip1grid from "./logo-strip/v1/fixtures/grid.json" with { type: "json" };
import logoStrip1placeholder from "./logo-strip/v1/fixtures/placeholder.json" with { type: "json" };
import logoStrip1row from "./logo-strip/v1/fixtures/row.json" with { type: "json" };
import postHeader1cover from "./post-header/v1/fixtures/cover.json" with { type: "json" };
import postHeader1placeholder from "./post-header/v1/fixtures/placeholder.json" with { type: "json" };
import postHeader1simple from "./post-header/v1/fixtures/simple.json" with { type: "json" };
import postList2cards from "./post-list/v2/fixtures/cards.json" with { type: "json" };
import postList2list from "./post-list/v2/fixtures/list.json" with { type: "json" };
import postList2placeholder from "./post-list/v2/fixtures/placeholder.json" with { type: "json" };
import quote1centered from "./quote/v1/fixtures/centered.json" with { type: "json" };
import quote1placeholder from "./quote/v1/fixtures/placeholder.json" with { type: "json" };
import quote1withPhoto from "./quote/v1/fixtures/with-photo.json" with { type: "json" };
import richText1narrow from "./rich-text/v1/fixtures/narrow.json" with { type: "json" };
import richText1placeholder from "./rich-text/v1/fixtures/placeholder.json" with { type: "json" };
import split1imageLeft from "./split/v1/fixtures/image-left.json" with { type: "json" };
import split1imageRight from "./split/v1/fixtures/image-right.json" with { type: "json" };
import split1placeholder from "./split/v1/fixtures/placeholder.json" with { type: "json" };
import stats1cards from "./stats/v1/fixtures/cards.json" with { type: "json" };
import stats1placeholder from "./stats/v1/fixtures/placeholder.json" with { type: "json" };
import stats1row from "./stats/v1/fixtures/row.json" with { type: "json" };
import teamGrid1fourColumns from "./team-grid/v1/fixtures/four-columns.json" with { type: "json" };
import teamGrid1placeholder from "./team-grid/v1/fixtures/placeholder.json" with { type: "json" };
import teamGrid1threeColumns from "./team-grid/v1/fixtures/three-columns.json" with { type: "json" };
import teamGrid2gridCentered from "./team-grid/v2/fixtures/grid-centered.json" with { type: "json" };
import teamGrid2grid from "./team-grid/v2/fixtures/grid.json" with { type: "json" };
import teamGrid2list from "./team-grid/v2/fixtures/list.json" with { type: "json" };
import teamGrid2overlay from "./team-grid/v2/fixtures/overlay.json" with { type: "json" };
import teamGrid2placeholder from "./team-grid/v2/fixtures/placeholder.json" with { type: "json" };
import teamMember1default from "./team-member/v1/fixtures/default.json" with { type: "json" };
import teamMember1placeholder from "./team-member/v1/fixtures/placeholder.json" with { type: "json" };
import teamMember2default from "./team-member/v2/fixtures/default.json" with { type: "json" };
import teamMember2placeholder from "./team-member/v2/fixtures/placeholder.json" with { type: "json" };
import timeline1agenda from "./timeline/v1/fixtures/agenda.json" with { type: "json" };
import timeline1placeholder from "./timeline/v1/fixtures/placeholder.json" with { type: "json" };
import timeline1vertical from "./timeline/v1/fixtures/vertical.json" with { type: "json" };
import timeline2agenda from "./timeline/v2/fixtures/agenda.json" with { type: "json" };
import timeline2horizontal from "./timeline/v2/fixtures/horizontal.json" with { type: "json" };
import timeline2placeholder from "./timeline/v2/fixtures/placeholder.json" with { type: "json" };
import timeline2vertical from "./timeline/v2/fixtures/vertical.json" with { type: "json" };

export const fixtureFiles = [
  { type: "call-to-action", version: 1, name: "banner", fixture: callToAction1banner },
  { type: "call-to-action", version: 1, name: "centered", fixture: callToAction1centered },
  { type: "call-to-action", version: 1, name: "placeholder", fixture: callToAction1placeholder },
  { type: "contact-details", version: 1, name: "columns", fixture: contactDetails1columns },
  { type: "contact-details", version: 1, name: "placeholder", fixture: contactDetails1placeholder },
  { type: "contact-details", version: 1, name: "stacked", fixture: contactDetails1stacked },
  { type: "contact-details", version: 2, name: "cards", fixture: contactDetails2cards },
  { type: "contact-details", version: 2, name: "columns", fixture: contactDetails2columns },
  { type: "contact-details", version: 2, name: "placeholder", fixture: contactDetails2placeholder },
  { type: "contact-details", version: 2, name: "split", fixture: contactDetails2split },
  { type: "event-card", version: 1, name: "default", fixture: eventCard1default },
  { type: "event-card", version: 1, name: "placeholder", fixture: eventCard1placeholder },
  { type: "event-card", version: 2, name: "default", fixture: eventCard2default },
  { type: "event-card", version: 2, name: "no-image", fixture: eventCard2noImage },
  { type: "event-card", version: 2, name: "placeholder", fixture: eventCard2placeholder },
  { type: "event-cards", version: 1, name: "grid", fixture: eventCards1grid },
  { type: "event-cards", version: 1, name: "list", fixture: eventCards1list },
  { type: "event-cards", version: 1, name: "placeholder", fixture: eventCards1placeholder },
  { type: "event-cards", version: 2, name: "grid-two", fixture: eventCards2gridTwo },
  { type: "event-cards", version: 2, name: "grid", fixture: eventCards2grid },
  { type: "event-cards", version: 2, name: "list", fixture: eventCards2list },
  { type: "event-cards", version: 2, name: "placeholder", fixture: eventCards2placeholder },
  { type: "faq", version: 1, name: "list", fixture: faq1list },
  { type: "faq", version: 1, name: "placeholder", fixture: faq1placeholder },
  { type: "faq", version: 1, name: "two-columns", fixture: faq1twoColumns },
  { type: "feature-grid", version: 1, name: "placeholder", fixture: featureGrid1placeholder },
  { type: "feature-grid", version: 1, name: "three-columns", fixture: featureGrid1threeColumns },
  { type: "feature-grid", version: 1, name: "two-columns", fixture: featureGrid1twoColumns },
  { type: "feature-grid", version: 2, name: "grid", fixture: featureGrid2grid },
  { type: "feature-grid", version: 2, name: "list", fixture: featureGrid2list },
  { type: "feature-grid", version: 2, name: "placeholder", fixture: featureGrid2placeholder },
  { type: "feature-grid", version: 2, name: "split", fixture: featureGrid2split },
  { type: "feature-item", version: 1, name: "default", fixture: featureItem1default },
  { type: "feature-item", version: 1, name: "placeholder", fixture: featureItem1placeholder },
  { type: "feature-item", version: 2, name: "default", fixture: featureItem2default },
  { type: "feature-item", version: 2, name: "image", fixture: featureItem2image },
  { type: "feature-item", version: 2, name: "placeholder", fixture: featureItem2placeholder },
  { type: "footer", version: 1, name: "columns", fixture: footer1columns },
  { type: "footer", version: 1, name: "simple", fixture: footer1simple },
  { type: "footer", version: 2, name: "centered", fixture: footer2centered },
  { type: "footer", version: 2, name: "columns", fixture: footer2columns },
  { type: "footer", version: 2, name: "simple", fixture: footer2simple },
  { type: "footer", version: 2, name: "wordmark", fixture: footer2wordmark },
  { type: "form-section", version: 1, name: "card", fixture: formSection1card },
  { type: "form-section", version: 1, name: "placeholder", fixture: formSection1placeholder },
  { type: "form-section", version: 1, name: "plain", fixture: formSection1plain },
  { type: "form-section", version: 2, name: "card", fixture: formSection2card },
  { type: "form-section", version: 2, name: "inline-inset", fixture: formSection2inlineInset },
  { type: "form-section", version: 2, name: "inline", fixture: formSection2inline },
  { type: "form-section", version: 2, name: "placeholder", fixture: formSection2placeholder },
  { type: "form-section", version: 2, name: "split", fixture: formSection2split },
  { type: "gallery", version: 1, name: "grid", fixture: gallery1grid },
  { type: "gallery", version: 1, name: "placeholder", fixture: gallery1placeholder },
  { type: "gallery", version: 1, name: "wide", fixture: gallery1wide },
  { type: "header", version: 1, name: "centered", fixture: header1centered },
  { type: "header", version: 1, name: "simple", fixture: header1simple },
  { type: "header", version: 2, name: "centered", fixture: header2centered },
  { type: "header", version: 2, name: "simple", fixture: header2simple },
  { type: "header", version: 3, name: "centered-logo", fixture: header3centeredLogo },
  { type: "header", version: 3, name: "centered-menu", fixture: header3centeredMenu },
  { type: "header", version: 3, name: "floating", fixture: header3floating },
  { type: "header", version: 3, name: "standard", fixture: header3standard },
  { type: "hero", version: 1, name: "centered", fixture: hero1centered },
  { type: "hero", version: 1, name: "placeholder", fixture: hero1placeholder },
  { type: "hero", version: 1, name: "split-image", fixture: hero1splitImage },
  { type: "hero", version: 2, name: "centered", fixture: hero2centered },
  { type: "hero", version: 2, name: "placeholder", fixture: hero2placeholder },
  { type: "hero", version: 2, name: "split-image", fixture: hero2splitImage },
  { type: "hero", version: 3, name: "centered", fixture: hero3centered },
  { type: "hero", version: 3, name: "full-bleed", fixture: hero3fullBleed },
  { type: "hero", version: 3, name: "placeholder", fixture: hero3placeholder },
  { type: "hero", version: 3, name: "split-image", fixture: hero3splitImage },
  { type: "hero", version: 4, name: "cover", fixture: hero4cover },
  { type: "hero", version: 4, name: "editorial", fixture: hero4editorial },
  { type: "hero", version: 4, name: "panel", fixture: hero4panel },
  { type: "hero", version: 4, name: "placeholder", fixture: hero4placeholder },
  { type: "hero", version: 4, name: "split", fixture: hero4split },
  { type: "hero", version: 4, name: "stacked", fixture: hero4stacked },
  { type: "image-caption", version: 1, name: "narrow", fixture: imageCaption1narrow },
  { type: "image-caption", version: 1, name: "placeholder", fixture: imageCaption1placeholder },
  { type: "image-caption", version: 1, name: "wide", fixture: imageCaption1wide },
  { type: "location", version: 1, name: "image-left", fixture: location1imageLeft },
  { type: "location", version: 1, name: "image-right", fixture: location1imageRight },
  { type: "location", version: 1, name: "placeholder", fixture: location1placeholder },
  { type: "location", version: 2, name: "placeholder", fixture: location2placeholder },
  { type: "location", version: 2, name: "split-start", fixture: location2splitStart },
  { type: "location", version: 2, name: "split", fixture: location2split },
  { type: "location", version: 2, name: "stacked", fixture: location2stacked },
  { type: "logo-strip", version: 1, name: "grid", fixture: logoStrip1grid },
  { type: "logo-strip", version: 1, name: "placeholder", fixture: logoStrip1placeholder },
  { type: "logo-strip", version: 1, name: "row", fixture: logoStrip1row },
  { type: "post-header", version: 1, name: "cover", fixture: postHeader1cover },
  { type: "post-header", version: 1, name: "placeholder", fixture: postHeader1placeholder },
  { type: "post-header", version: 1, name: "simple", fixture: postHeader1simple },
  { type: "post-list", version: 2, name: "cards", fixture: postList2cards },
  { type: "post-list", version: 2, name: "list", fixture: postList2list },
  { type: "post-list", version: 2, name: "placeholder", fixture: postList2placeholder },
  { type: "quote", version: 1, name: "centered", fixture: quote1centered },
  { type: "quote", version: 1, name: "placeholder", fixture: quote1placeholder },
  { type: "quote", version: 1, name: "with-photo", fixture: quote1withPhoto },
  { type: "rich-text", version: 1, name: "narrow", fixture: richText1narrow },
  { type: "rich-text", version: 1, name: "placeholder", fixture: richText1placeholder },
  { type: "split", version: 1, name: "image-left", fixture: split1imageLeft },
  { type: "split", version: 1, name: "image-right", fixture: split1imageRight },
  { type: "split", version: 1, name: "placeholder", fixture: split1placeholder },
  { type: "stats", version: 1, name: "cards", fixture: stats1cards },
  { type: "stats", version: 1, name: "placeholder", fixture: stats1placeholder },
  { type: "stats", version: 1, name: "row", fixture: stats1row },
  { type: "team-grid", version: 1, name: "four-columns", fixture: teamGrid1fourColumns },
  { type: "team-grid", version: 1, name: "placeholder", fixture: teamGrid1placeholder },
  { type: "team-grid", version: 1, name: "three-columns", fixture: teamGrid1threeColumns },
  { type: "team-grid", version: 2, name: "grid-centered", fixture: teamGrid2gridCentered },
  { type: "team-grid", version: 2, name: "grid", fixture: teamGrid2grid },
  { type: "team-grid", version: 2, name: "list", fixture: teamGrid2list },
  { type: "team-grid", version: 2, name: "overlay", fixture: teamGrid2overlay },
  { type: "team-grid", version: 2, name: "placeholder", fixture: teamGrid2placeholder },
  { type: "team-member", version: 1, name: "default", fixture: teamMember1default },
  { type: "team-member", version: 1, name: "placeholder", fixture: teamMember1placeholder },
  { type: "team-member", version: 2, name: "default", fixture: teamMember2default },
  { type: "team-member", version: 2, name: "placeholder", fixture: teamMember2placeholder },
  { type: "timeline", version: 1, name: "agenda", fixture: timeline1agenda },
  { type: "timeline", version: 1, name: "placeholder", fixture: timeline1placeholder },
  { type: "timeline", version: 1, name: "vertical", fixture: timeline1vertical },
  { type: "timeline", version: 2, name: "agenda", fixture: timeline2agenda },
  { type: "timeline", version: 2, name: "horizontal", fixture: timeline2horizontal },
  { type: "timeline", version: 2, name: "placeholder", fixture: timeline2placeholder },
  { type: "timeline", version: 2, name: "vertical", fixture: timeline2vertical },
] as const;
