// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import bento1grid from "./bento/v1/fixtures/grid.json" with { type: "json" };
import bento1placeholder from "./bento/v1/fixtures/placeholder.json" with { type: "json" };
import bento1showcase from "./bento/v1/fixtures/showcase.json" with { type: "json" };
import bentoTile1image from "./bento-tile/v1/fixtures/image.json" with { type: "json" };
import bentoTile1placeholder from "./bento-tile/v1/fixtures/placeholder.json" with { type: "json" };
import callToAction1banner from "./call-to-action/v1/fixtures/banner.json" with { type: "json" };
import callToAction1centered from "./call-to-action/v1/fixtures/centered.json" with { type: "json" };
import callToAction1placeholder from "./call-to-action/v1/fixtures/placeholder.json" with { type: "json" };
import callToAction2centered from "./call-to-action/v2/fixtures/centered.json" with { type: "json" };
import callToAction2image from "./call-to-action/v2/fixtures/image.json" with { type: "json" };
import callToAction2panelWords from "./call-to-action/v2/fixtures/panel-words.json" with { type: "json" };
import callToAction2panel from "./call-to-action/v2/fixtures/panel.json" with { type: "json" };
import callToAction2placeholder from "./call-to-action/v2/fixtures/placeholder.json" with { type: "json" };
import callToAction2split from "./call-to-action/v2/fixtures/split.json" with { type: "json" };
import contactDetails1columns from "./contact-details/v1/fixtures/columns.json" with { type: "json" };
import contactDetails1placeholder from "./contact-details/v1/fixtures/placeholder.json" with { type: "json" };
import contactDetails1stacked from "./contact-details/v1/fixtures/stacked.json" with { type: "json" };
import eventCard1default from "./event-card/v1/fixtures/default.json" with { type: "json" };
import eventCard1placeholder from "./event-card/v1/fixtures/placeholder.json" with { type: "json" };
import eventCards1grid from "./event-cards/v1/fixtures/grid.json" with { type: "json" };
import eventCards1list from "./event-cards/v1/fixtures/list.json" with { type: "json" };
import eventCards1placeholder from "./event-cards/v1/fixtures/placeholder.json" with { type: "json" };
import faq1list from "./faq/v1/fixtures/list.json" with { type: "json" };
import faq1placeholder from "./faq/v1/fixtures/placeholder.json" with { type: "json" };
import faq1twoColumns from "./faq/v1/fixtures/two-columns.json" with { type: "json" };
import featureGrid2grid from "./feature-grid/v2/fixtures/grid.json" with { type: "json" };
import featureGrid2list from "./feature-grid/v2/fixtures/list.json" with { type: "json" };
import featureGrid2placeholder from "./feature-grid/v2/fixtures/placeholder.json" with { type: "json" };
import featureGrid2split from "./feature-grid/v2/fixtures/split.json" with { type: "json" };
import featureItem2default from "./feature-item/v2/fixtures/default.json" with { type: "json" };
import featureItem2image from "./feature-item/v2/fixtures/image.json" with { type: "json" };
import featureItem2placeholder from "./feature-item/v2/fixtures/placeholder.json" with { type: "json" };
import footer2centered from "./footer/v2/fixtures/centered.json" with { type: "json" };
import footer2columns from "./footer/v2/fixtures/columns.json" with { type: "json" };
import footer2simple from "./footer/v2/fixtures/simple.json" with { type: "json" };
import footer2wordmark from "./footer/v2/fixtures/wordmark.json" with { type: "json" };
import formSection1card from "./form-section/v1/fixtures/card.json" with { type: "json" };
import formSection1placeholder from "./form-section/v1/fixtures/placeholder.json" with { type: "json" };
import formSection1plain from "./form-section/v1/fixtures/plain.json" with { type: "json" };
import gallery1grid from "./gallery/v1/fixtures/grid.json" with { type: "json" };
import gallery1placeholder from "./gallery/v1/fixtures/placeholder.json" with { type: "json" };
import gallery1wide from "./gallery/v1/fixtures/wide.json" with { type: "json" };
import header3centeredLogo from "./header/v3/fixtures/centered-logo.json" with { type: "json" };
import header3centeredMenu from "./header/v3/fixtures/centered-menu.json" with { type: "json" };
import header3floating from "./header/v3/fixtures/floating.json" with { type: "json" };
import header3standard from "./header/v3/fixtures/standard.json" with { type: "json" };
import hero4cover from "./hero/v4/fixtures/cover.json" with { type: "json" };
import hero4editorial from "./hero/v4/fixtures/editorial.json" with { type: "json" };
import hero4panel from "./hero/v4/fixtures/panel.json" with { type: "json" };
import hero4phone from "./hero/v4/fixtures/phone.json" with { type: "json" };
import hero4placeholder from "./hero/v4/fixtures/placeholder.json" with { type: "json" };
import hero4split from "./hero/v4/fixtures/split.json" with { type: "json" };
import hero4stacked from "./hero/v4/fixtures/stacked.json" with { type: "json" };
import imageCaption1narrow from "./image-caption/v1/fixtures/narrow.json" with { type: "json" };
import imageCaption1placeholder from "./image-caption/v1/fixtures/placeholder.json" with { type: "json" };
import imageCaption1wide from "./image-caption/v1/fixtures/wide.json" with { type: "json" };
import location1imageLeft from "./location/v1/fixtures/image-left.json" with { type: "json" };
import location1imageRight from "./location/v1/fixtures/image-right.json" with { type: "json" };
import location1placeholder from "./location/v1/fixtures/placeholder.json" with { type: "json" };
import logoStrip1grid from "./logo-strip/v1/fixtures/grid.json" with { type: "json" };
import logoStrip1placeholder from "./logo-strip/v1/fixtures/placeholder.json" with { type: "json" };
import logoStrip1row from "./logo-strip/v1/fixtures/row.json" with { type: "json" };
import logoStrip2grid from "./logo-strip/v2/fixtures/grid.json" with { type: "json" };
import logoStrip2marquee from "./logo-strip/v2/fixtures/marquee.json" with { type: "json" };
import logoStrip2placeholder from "./logo-strip/v2/fixtures/placeholder.json" with { type: "json" };
import logoStrip2row from "./logo-strip/v2/fixtures/row.json" with { type: "json" };
import logoStrip2split from "./logo-strip/v2/fixtures/split.json" with { type: "json" };
import postHeader1cover from "./post-header/v1/fixtures/cover.json" with { type: "json" };
import postHeader1placeholder from "./post-header/v1/fixtures/placeholder.json" with { type: "json" };
import postHeader1simple from "./post-header/v1/fixtures/simple.json" with { type: "json" };
import postList2cards from "./post-list/v2/fixtures/cards.json" with { type: "json" };
import postList2list from "./post-list/v2/fixtures/list.json" with { type: "json" };
import postList2placeholder from "./post-list/v2/fixtures/placeholder.json" with { type: "json" };
import quote1centered from "./quote/v1/fixtures/centered.json" with { type: "json" };
import quote1placeholder from "./quote/v1/fixtures/placeholder.json" with { type: "json" };
import quote1withPhoto from "./quote/v1/fixtures/with-photo.json" with { type: "json" };
import richText1narrow from "./rich-text/v1/fixtures/narrow.json" with { type: "json" };
import richText1placeholder from "./rich-text/v1/fixtures/placeholder.json" with { type: "json" };
import split1imageLeft from "./split/v1/fixtures/image-left.json" with { type: "json" };
import split1imageRight from "./split/v1/fixtures/image-right.json" with { type: "json" };
import split1placeholder from "./split/v1/fixtures/placeholder.json" with { type: "json" };
import split2bleedInset from "./split/v2/fixtures/bleed-inset.json" with { type: "json" };
import split2bleed from "./split/v2/fixtures/bleed.json" with { type: "json" };
import split2placeholder from "./split/v2/fixtures/placeholder.json" with { type: "json" };
import split2standardFramed from "./split/v2/fixtures/standard-framed.json" with { type: "json" };
import split2standard from "./split/v2/fixtures/standard.json" with { type: "json" };
import statement1brand from "./statement/v1/fixtures/brand.json" with { type: "json" };
import statement1center from "./statement/v1/fixtures/center.json" with { type: "json" };
import statement1placeholder from "./statement/v1/fixtures/placeholder.json" with { type: "json" };
import statement1start from "./statement/v1/fixtures/start.json" with { type: "json" };
import stats1cards from "./stats/v1/fixtures/cards.json" with { type: "json" };
import stats1placeholder from "./stats/v1/fixtures/placeholder.json" with { type: "json" };
import stats1row from "./stats/v1/fixtures/row.json" with { type: "json" };
import stats2cards from "./stats/v2/fixtures/cards.json" with { type: "json" };
import stats2placeholder from "./stats/v2/fixtures/placeholder.json" with { type: "json" };
import stats2rowCentered from "./stats/v2/fixtures/row-centered.json" with { type: "json" };
import stats2row from "./stats/v2/fixtures/row.json" with { type: "json" };
import stats2split from "./stats/v2/fixtures/split.json" with { type: "json" };
import teamGrid1fourColumns from "./team-grid/v1/fixtures/four-columns.json" with { type: "json" };
import teamGrid1placeholder from "./team-grid/v1/fixtures/placeholder.json" with { type: "json" };
import teamGrid1threeColumns from "./team-grid/v1/fixtures/three-columns.json" with { type: "json" };
import teamMember1default from "./team-member/v1/fixtures/default.json" with { type: "json" };
import teamMember1placeholder from "./team-member/v1/fixtures/placeholder.json" with { type: "json" };
import timeline1agenda from "./timeline/v1/fixtures/agenda.json" with { type: "json" };
import timeline1placeholder from "./timeline/v1/fixtures/placeholder.json" with { type: "json" };
import timeline1vertical from "./timeline/v1/fixtures/vertical.json" with { type: "json" };

export const fixtureFiles = [
  { type: "bento", version: 1, name: "grid", fixture: bento1grid },
  { type: "bento", version: 1, name: "placeholder", fixture: bento1placeholder },
  { type: "bento", version: 1, name: "showcase", fixture: bento1showcase },
  { type: "bento-tile", version: 1, name: "image", fixture: bentoTile1image },
  { type: "bento-tile", version: 1, name: "placeholder", fixture: bentoTile1placeholder },
  { type: "call-to-action", version: 1, name: "banner", fixture: callToAction1banner },
  { type: "call-to-action", version: 1, name: "centered", fixture: callToAction1centered },
  { type: "call-to-action", version: 1, name: "placeholder", fixture: callToAction1placeholder },
  { type: "call-to-action", version: 2, name: "centered", fixture: callToAction2centered },
  { type: "call-to-action", version: 2, name: "image", fixture: callToAction2image },
  { type: "call-to-action", version: 2, name: "panel-words", fixture: callToAction2panelWords },
  { type: "call-to-action", version: 2, name: "panel", fixture: callToAction2panel },
  { type: "call-to-action", version: 2, name: "placeholder", fixture: callToAction2placeholder },
  { type: "call-to-action", version: 2, name: "split", fixture: callToAction2split },
  { type: "contact-details", version: 1, name: "columns", fixture: contactDetails1columns },
  { type: "contact-details", version: 1, name: "placeholder", fixture: contactDetails1placeholder },
  { type: "contact-details", version: 1, name: "stacked", fixture: contactDetails1stacked },
  { type: "event-card", version: 1, name: "default", fixture: eventCard1default },
  { type: "event-card", version: 1, name: "placeholder", fixture: eventCard1placeholder },
  { type: "event-cards", version: 1, name: "grid", fixture: eventCards1grid },
  { type: "event-cards", version: 1, name: "list", fixture: eventCards1list },
  { type: "event-cards", version: 1, name: "placeholder", fixture: eventCards1placeholder },
  { type: "faq", version: 1, name: "list", fixture: faq1list },
  { type: "faq", version: 1, name: "placeholder", fixture: faq1placeholder },
  { type: "faq", version: 1, name: "two-columns", fixture: faq1twoColumns },
  { type: "feature-grid", version: 2, name: "grid", fixture: featureGrid2grid },
  { type: "feature-grid", version: 2, name: "list", fixture: featureGrid2list },
  { type: "feature-grid", version: 2, name: "placeholder", fixture: featureGrid2placeholder },
  { type: "feature-grid", version: 2, name: "split", fixture: featureGrid2split },
  { type: "feature-item", version: 2, name: "default", fixture: featureItem2default },
  { type: "feature-item", version: 2, name: "image", fixture: featureItem2image },
  { type: "feature-item", version: 2, name: "placeholder", fixture: featureItem2placeholder },
  { type: "footer", version: 2, name: "centered", fixture: footer2centered },
  { type: "footer", version: 2, name: "columns", fixture: footer2columns },
  { type: "footer", version: 2, name: "simple", fixture: footer2simple },
  { type: "footer", version: 2, name: "wordmark", fixture: footer2wordmark },
  { type: "form-section", version: 1, name: "card", fixture: formSection1card },
  { type: "form-section", version: 1, name: "placeholder", fixture: formSection1placeholder },
  { type: "form-section", version: 1, name: "plain", fixture: formSection1plain },
  { type: "gallery", version: 1, name: "grid", fixture: gallery1grid },
  { type: "gallery", version: 1, name: "placeholder", fixture: gallery1placeholder },
  { type: "gallery", version: 1, name: "wide", fixture: gallery1wide },
  { type: "header", version: 3, name: "centered-logo", fixture: header3centeredLogo },
  { type: "header", version: 3, name: "centered-menu", fixture: header3centeredMenu },
  { type: "header", version: 3, name: "floating", fixture: header3floating },
  { type: "header", version: 3, name: "standard", fixture: header3standard },
  { type: "hero", version: 4, name: "cover", fixture: hero4cover },
  { type: "hero", version: 4, name: "editorial", fixture: hero4editorial },
  { type: "hero", version: 4, name: "panel", fixture: hero4panel },
  { type: "hero", version: 4, name: "phone", fixture: hero4phone },
  { type: "hero", version: 4, name: "placeholder", fixture: hero4placeholder },
  { type: "hero", version: 4, name: "split", fixture: hero4split },
  { type: "hero", version: 4, name: "stacked", fixture: hero4stacked },
  { type: "image-caption", version: 1, name: "narrow", fixture: imageCaption1narrow },
  { type: "image-caption", version: 1, name: "placeholder", fixture: imageCaption1placeholder },
  { type: "image-caption", version: 1, name: "wide", fixture: imageCaption1wide },
  { type: "location", version: 1, name: "image-left", fixture: location1imageLeft },
  { type: "location", version: 1, name: "image-right", fixture: location1imageRight },
  { type: "location", version: 1, name: "placeholder", fixture: location1placeholder },
  { type: "logo-strip", version: 1, name: "grid", fixture: logoStrip1grid },
  { type: "logo-strip", version: 1, name: "placeholder", fixture: logoStrip1placeholder },
  { type: "logo-strip", version: 1, name: "row", fixture: logoStrip1row },
  { type: "logo-strip", version: 2, name: "grid", fixture: logoStrip2grid },
  { type: "logo-strip", version: 2, name: "marquee", fixture: logoStrip2marquee },
  { type: "logo-strip", version: 2, name: "placeholder", fixture: logoStrip2placeholder },
  { type: "logo-strip", version: 2, name: "row", fixture: logoStrip2row },
  { type: "logo-strip", version: 2, name: "split", fixture: logoStrip2split },
  { type: "post-header", version: 1, name: "cover", fixture: postHeader1cover },
  { type: "post-header", version: 1, name: "placeholder", fixture: postHeader1placeholder },
  { type: "post-header", version: 1, name: "simple", fixture: postHeader1simple },
  { type: "post-list", version: 2, name: "cards", fixture: postList2cards },
  { type: "post-list", version: 2, name: "list", fixture: postList2list },
  { type: "post-list", version: 2, name: "placeholder", fixture: postList2placeholder },
  { type: "quote", version: 1, name: "centered", fixture: quote1centered },
  { type: "quote", version: 1, name: "placeholder", fixture: quote1placeholder },
  { type: "quote", version: 1, name: "with-photo", fixture: quote1withPhoto },
  { type: "rich-text", version: 1, name: "narrow", fixture: richText1narrow },
  { type: "rich-text", version: 1, name: "placeholder", fixture: richText1placeholder },
  { type: "split", version: 1, name: "image-left", fixture: split1imageLeft },
  { type: "split", version: 1, name: "image-right", fixture: split1imageRight },
  { type: "split", version: 1, name: "placeholder", fixture: split1placeholder },
  { type: "split", version: 2, name: "bleed-inset", fixture: split2bleedInset },
  { type: "split", version: 2, name: "bleed", fixture: split2bleed },
  { type: "split", version: 2, name: "placeholder", fixture: split2placeholder },
  { type: "split", version: 2, name: "standard-framed", fixture: split2standardFramed },
  { type: "split", version: 2, name: "standard", fixture: split2standard },
  { type: "statement", version: 1, name: "brand", fixture: statement1brand },
  { type: "statement", version: 1, name: "center", fixture: statement1center },
  { type: "statement", version: 1, name: "placeholder", fixture: statement1placeholder },
  { type: "statement", version: 1, name: "start", fixture: statement1start },
  { type: "stats", version: 1, name: "cards", fixture: stats1cards },
  { type: "stats", version: 1, name: "placeholder", fixture: stats1placeholder },
  { type: "stats", version: 1, name: "row", fixture: stats1row },
  { type: "stats", version: 2, name: "cards", fixture: stats2cards },
  { type: "stats", version: 2, name: "placeholder", fixture: stats2placeholder },
  { type: "stats", version: 2, name: "row-centered", fixture: stats2rowCentered },
  { type: "stats", version: 2, name: "row", fixture: stats2row },
  { type: "stats", version: 2, name: "split", fixture: stats2split },
  { type: "team-grid", version: 1, name: "four-columns", fixture: teamGrid1fourColumns },
  { type: "team-grid", version: 1, name: "placeholder", fixture: teamGrid1placeholder },
  { type: "team-grid", version: 1, name: "three-columns", fixture: teamGrid1threeColumns },
  { type: "team-member", version: 1, name: "default", fixture: teamMember1default },
  { type: "team-member", version: 1, name: "placeholder", fixture: teamMember1placeholder },
  { type: "timeline", version: 1, name: "agenda", fixture: timeline1agenda },
  { type: "timeline", version: 1, name: "placeholder", fixture: timeline1placeholder },
  { type: "timeline", version: 1, name: "vertical", fixture: timeline1vertical },
] as const;
