// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import callToAction1banner from "./call-to-action/v1/fixtures/banner.json" with { type: "json" };
import callToAction1centered from "./call-to-action/v1/fixtures/centered.json" with { type: "json" };
import featureGrid1threeColumns from "./feature-grid/v1/fixtures/three-columns.json" with { type: "json" };
import featureGrid1twoColumns from "./feature-grid/v1/fixtures/two-columns.json" with { type: "json" };
import featureItem1default from "./feature-item/v1/fixtures/default.json" with { type: "json" };
import footer1columns from "./footer/v1/fixtures/columns.json" with { type: "json" };
import footer1simple from "./footer/v1/fixtures/simple.json" with { type: "json" };
import formSection1card from "./form-section/v1/fixtures/card.json" with { type: "json" };
import formSection1plain from "./form-section/v1/fixtures/plain.json" with { type: "json" };
import gallery1grid from "./gallery/v1/fixtures/grid.json" with { type: "json" };
import gallery1wide from "./gallery/v1/fixtures/wide.json" with { type: "json" };
import header1centered from "./header/v1/fixtures/centered.json" with { type: "json" };
import header1simple from "./header/v1/fixtures/simple.json" with { type: "json" };
import hero1centered from "./hero/v1/fixtures/centered.json" with { type: "json" };
import hero1splitImage from "./hero/v1/fixtures/split-image.json" with { type: "json" };
import postList1cards from "./post-list/v1/fixtures/cards.json" with { type: "json" };
import postList1list from "./post-list/v1/fixtures/list.json" with { type: "json" };
import richText1narrow from "./rich-text/v1/fixtures/narrow.json" with { type: "json" };
import split1imageLeft from "./split/v1/fixtures/image-left.json" with { type: "json" };
import split1imageRight from "./split/v1/fixtures/image-right.json" with { type: "json" };

export const fixtureFiles = [
  { type: "call-to-action", version: 1, name: "banner", fixture: callToAction1banner },
  { type: "call-to-action", version: 1, name: "centered", fixture: callToAction1centered },
  { type: "feature-grid", version: 1, name: "three-columns", fixture: featureGrid1threeColumns },
  { type: "feature-grid", version: 1, name: "two-columns", fixture: featureGrid1twoColumns },
  { type: "feature-item", version: 1, name: "default", fixture: featureItem1default },
  { type: "footer", version: 1, name: "columns", fixture: footer1columns },
  { type: "footer", version: 1, name: "simple", fixture: footer1simple },
  { type: "form-section", version: 1, name: "card", fixture: formSection1card },
  { type: "form-section", version: 1, name: "plain", fixture: formSection1plain },
  { type: "gallery", version: 1, name: "grid", fixture: gallery1grid },
  { type: "gallery", version: 1, name: "wide", fixture: gallery1wide },
  { type: "header", version: 1, name: "centered", fixture: header1centered },
  { type: "header", version: 1, name: "simple", fixture: header1simple },
  { type: "hero", version: 1, name: "centered", fixture: hero1centered },
  { type: "hero", version: 1, name: "split-image", fixture: hero1splitImage },
  { type: "post-list", version: 1, name: "cards", fixture: postList1cards },
  { type: "post-list", version: 1, name: "list", fixture: postList1list },
  { type: "rich-text", version: 1, name: "narrow", fixture: richText1narrow },
  { type: "split", version: 1, name: "image-left", fixture: split1imageLeft },
  { type: "split", version: 1, name: "image-right", fixture: split1imageRight },
] as const;
