// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import callToAction from "./call-to-action/presentation.ts";
import contactDetails from "./contact-details/presentation.ts";
import eventCard from "./event-card/presentation.ts";
import eventCards from "./event-cards/presentation.ts";
import faq from "./faq/presentation.ts";
import featureGrid from "./feature-grid/presentation.ts";
import featureItem from "./feature-item/presentation.ts";
import footer from "./footer/presentation.ts";
import formSection from "./form-section/presentation.ts";
import gallery from "./gallery/presentation.ts";
import header from "./header/presentation.ts";
import hero from "./hero/presentation.ts";
import imageCaption from "./image-caption/presentation.ts";
import location from "./location/presentation.ts";
import logoStrip from "./logo-strip/presentation.ts";
import postHeader from "./post-header/presentation.ts";
import postList from "./post-list/presentation.ts";
import quote from "./quote/presentation.ts";
import richText from "./rich-text/presentation.ts";
import split from "./split/presentation.ts";
import stats from "./stats/presentation.ts";
import teamGrid from "./team-grid/presentation.ts";
import teamMember from "./team-member/presentation.ts";
import testimonial from "./testimonial/presentation.ts";
import testimonials from "./testimonials/presentation.ts";
import timeline from "./timeline/presentation.ts";

export const presentations = {
  "call-to-action": callToAction,
  "contact-details": contactDetails,
  "event-card": eventCard,
  "event-cards": eventCards,
  "faq": faq,
  "feature-grid": featureGrid,
  "feature-item": featureItem,
  "footer": footer,
  "form-section": formSection,
  "gallery": gallery,
  "header": header,
  "hero": hero,
  "image-caption": imageCaption,
  "location": location,
  "logo-strip": logoStrip,
  "post-header": postHeader,
  "post-list": postList,
  "quote": quote,
  "rich-text": richText,
  "split": split,
  "stats": stats,
  "team-grid": teamGrid,
  "team-member": teamMember,
  "testimonial": testimonial,
  "testimonials": testimonials,
  "timeline": timeline,
};
