// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import type { BlockDefinition } from "./block.tsx";

export const registry: Readonly<
  Record<string, () => Promise<{ readonly default: BlockDefinition }>>
> = {
  "call-to-action@1": () => import("./call-to-action/v1/index.tsx"),
  "contact-details@1": () => import("./contact-details/v1/index.tsx"),
  "event-card@1": () => import("./event-card/v1/index.tsx"),
  "event-cards@1": () => import("./event-cards/v1/index.tsx"),
  "faq@1": () => import("./faq/v1/index.tsx"),
  "feature-grid@2": () => import("./feature-grid/v2/index.tsx"),
  "feature-item@2": () => import("./feature-item/v2/index.tsx"),
  "footer@2": () => import("./footer/v2/index.tsx"),
  "form-section@1": () => import("./form-section/v1/index.tsx"),
  "gallery@1": () => import("./gallery/v1/index.tsx"),
  "header@3": () => import("./header/v3/index.tsx"),
  "hero@4": () => import("./hero/v4/index.tsx"),
  "image-caption@1": () => import("./image-caption/v1/index.tsx"),
  "location@1": () => import("./location/v1/index.tsx"),
  "logo-strip@1": () => import("./logo-strip/v1/index.tsx"),
  "post-header@1": () => import("./post-header/v1/index.tsx"),
  "post-list@2": () => import("./post-list/v2/index.tsx"),
  "quote@1": () => import("./quote/v1/index.tsx"),
  "rich-text@1": () => import("./rich-text/v1/index.tsx"),
  "split@1": () => import("./split/v1/index.tsx"),
  "stats@1": () => import("./stats/v1/index.tsx"),
  "team-grid@1": () => import("./team-grid/v1/index.tsx"),
  "team-member@1": () => import("./team-member/v1/index.tsx"),
  "timeline@1": () => import("./timeline/v1/index.tsx"),
};
