// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import type { BlockDefinition } from "./block.tsx";

export const registry: Readonly<
  Record<string, () => Promise<{ readonly default: BlockDefinition }>>
> = {
  "call-to-action@1": () => import("./call-to-action/v1/index.tsx"),
  "hero@1": () => import("./hero/v1/index.tsx"),
  "rich-text@1": () => import("./rich-text/v1/index.tsx"),
};
