// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.
import bento from "./bento/sample.ts";
import bentoTile from "./bento-tile/sample.ts";
import callToAction from "./call-to-action/sample.ts";
import contactDetails from "./contact-details/sample.ts";
import eventCard from "./event-card/sample.ts";
import eventCards from "./event-cards/sample.ts";
import faq from "./faq/sample.ts";
import featureGrid from "./feature-grid/sample.ts";
import featureItem from "./feature-item/sample.ts";
import footer from "./footer/sample.ts";
import formSection from "./form-section/sample.ts";
import gallery from "./gallery/sample.ts";
import header from "./header/sample.ts";
import hero from "./hero/sample.ts";
import imageCaption from "./image-caption/sample.ts";
import location from "./location/sample.ts";
import logoStrip from "./logo-strip/sample.ts";
import postHeader from "./post-header/sample.ts";
import postList from "./post-list/sample.ts";
import pricing from "./pricing/sample.ts";
import pricingPlan from "./pricing-plan/sample.ts";
import quote from "./quote/sample.ts";
import richText from "./rich-text/sample.ts";
import split from "./split/sample.ts";
import statement from "./statement/sample.ts";
import stats from "./stats/sample.ts";
import steps from "./steps/sample.ts";
import teamGrid from "./team-grid/sample.ts";
import teamMember from "./team-member/sample.ts";
import testimonial from "./testimonial/sample.ts";
import testimonials from "./testimonials/sample.ts";
import timeline from "./timeline/sample.ts";

export const samples = {
  "bento": bento,
  "bento-tile": bentoTile,
  "call-to-action": callToAction,
  "contact-details": contactDetails,
  "event-card": eventCard,
  "event-cards": eventCards,
  "faq": faq,
  "feature-grid": featureGrid,
  "feature-item": featureItem,
  "footer": footer,
  "form-section": formSection,
  "gallery": gallery,
  "header": header,
  "hero": hero,
  "image-caption": imageCaption,
  "location": location,
  "logo-strip": logoStrip,
  "post-header": postHeader,
  "post-list": postList,
  "pricing": pricing,
  "pricing-plan": pricingPlan,
  "quote": quote,
  "rich-text": richText,
  "split": split,
  "statement": statement,
  "stats": stats,
  "steps": steps,
  "team-grid": teamGrid,
  "team-member": teamMember,
  "testimonial": testimonial,
  "testimonials": testimonials,
  "timeline": timeline,
};
