import { readdir, readFile, writeFile } from "node:fs/promises";

const source = new URL("../src/", import.meta.url);
const target = new URL("registry.gen.ts", source);

/** Builds the registry source from the block version folders under src/. */
export const registrySource = async () => {
  const entries: Array<string> = [];
  for (const type of (await readdir(source, { withFileTypes: true })).filter((entry) =>
    entry.isDirectory(),
  )) {
    const versions = await readdir(new URL(`${type.name}/`, source));
    for (const version of versions.filter((name) => /^v\d+$/.test(name))) {
      entries.push(
        `  "${type.name}@${version.slice(1)}": () => import("./${type.name}/${version}/index.tsx"),`,
      );
    }
  }
  return [
    "// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.",
    'import type { BlockDefinition } from "./block.tsx";',
    "",
    "export const registry: Readonly<",
    "  Record<string, () => Promise<{ readonly default: BlockDefinition }>>",
    "> = {",
    ...entries.toSorted(),
    "};",
    "",
  ].join("\n");
};

if (import.meta.main) {
  const next = await registrySource();
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== next) await writeFile(target, next);
}
