import { readdir, readFile, writeFile } from "node:fs/promises";

const source = new URL("../src/", import.meta.url);

const header =
  "// Generated by scripts/generate-registry.ts. Run `pnpm --filter @repo/blocks generate`.";

/** Every block version folder under src/, as `[type, version]`. */
const blockVersions = async () => {
  const found: Array<readonly [string, number]> = [];
  for (const type of await readdir(source, { withFileTypes: true })) {
    if (!type.isDirectory()) continue;
    for (const version of await readdir(new URL(`${type.name}/`, source)))
      if (/^v\d+$/.test(version)) found.push([type.name, Number(version.slice(1))]);
  }
  return found.toSorted(([a, x], [b, y]) => (a === b ? x - y : a < b ? -1 : 1));
};

/** Builds the registry source from the block version folders under src/. */
export const registrySource = async () =>
  [
    header,
    'import type { BlockDefinition } from "./block.tsx";',
    "",
    "export const registry: Readonly<",
    "  Record<string, () => Promise<{ readonly default: BlockDefinition }>>",
    "> = {",
    ...(await blockVersions()).map(
      ([type, version]) =>
        `  "${type}@${version}": () => import("./${type}/v${version}/index.tsx"),`,
    ),
    "};",
    "",
  ].join("\n");

/** Builds the fixture list source from the fixtures folder of every block version. */
export const fixturesSource = async () => {
  const imports: Array<string> = [];
  const entries: Array<string> = [];
  for (const [type, version] of await blockVersions()) {
    const files = await readdir(new URL(`${type}/v${version}/fixtures/`, source)).catch(() => []);
    for (const file of files.filter((name) => name.endsWith(".json")).toSorted()) {
      const name = file.replace(/\.json$/, "");
      const binding = `${type}${version}${name}`.replace(/[^A-Za-z0-9]+(.)/g, (_, next: string) =>
        next.toUpperCase(),
      );
      imports.push(
        `import ${binding} from "./${type}/v${version}/fixtures/${file}" with { type: "json" };`,
      );
      entries.push(
        `  { type: "${type}", version: ${version}, name: "${name}", fixture: ${binding} },`,
      );
    }
  }
  return [
    header,
    ...imports,
    "",
    "export const fixtureFiles = [",
    ...entries,
    "] as const;",
    "",
  ].join("\n");
};

const write = async (file: string, next: string) => {
  const target = new URL(file, source);
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== next) await writeFile(target, next);
};

if (import.meta.main) {
  await write("registry.gen.ts", await registrySource());
  await write("fixtures.gen.ts", await fixturesSource());
}
